### PR TITLE
HTML For Header and Footer

### PR DESCRIPTION
**Pull request by NicoClack**
I've written the HTML for the header and footer. I've also added the necessary images for the social media icons.

### Potential Areas to Discuss

- My class names aren't very BEM-like, so I should probably update them.
- I used h3s in the footer for the Company and Legal headers. This seems right in terms of the hierarchy but the corresponding h2 will be the "What people think about us". Could we use a blank h2 maybe? Or just paragraphs again? They _are_ in different sections though, so hopefully screen readers/search engines won't connect them.
- I replaced the "All Rights Reserved" part of the original design with "Licensed under MIT", which links to the license.
- Should I change it to use absolute paths? Copying this to the About page will currently require a bunch of small changes. The downside of using them is that we have to hardcode the repository name ("technative-academy") into the paths. But future pages should be able to reuse the About variant, unless they've got another layer in the path like "/legal/tos" rather than "/tos" (not that we're making these pages).

### Unrelated Changes

- Fixed the stylesheet `link`s in `about/index.html`

Partially resolves: https://trello.com/c/bmdVsaS9

### CODE REVIEW

**Review by Jo-Pickering — COMMENTED** [review]
Hi Nico,

I'm not too sure that BEM matters too much for the header/footer as once it's set it'll just stay the same? 
I'm happy with the liscence swap in. Makes sense for the project.
I'd be tempted to use absolute file paths incase we get round to creating the products page.  It should make copy and pasting into the new file a bit easier for us (as it will for adding it to the about about page).

Happy for you to use whichever, h3 or p, that you see fit at this point.

Also - well dont for linking the Trello card! Absolutely forgot on my last one!!

**Comment by NicoClack** [comment]
@Jo-Pickering 
> I'm not too sure that BEM matters too much for the header/footer as once it's set it'll just stay the same?

Yeah, it might not be worth redoing. I haven't entirely got the hang of BEM yet so it might take a while.

I'll wait for Helder's thoughts on the rest.

**Comment by NicoClack** [comment]
I'll change them to absolutes and merge.

**Comment by NicoClack** [comment]
Just changed them to absolute paths. For development, we'll now need to run Live Server from the parent folder so the prefix works correctly. So I've got my clone of the repository at "C:\Users\nico\Documents\TechNative Bootcamp\Code\milliways_restaurant" and I have a second VSCode window open in "C:\Users\nico\Documents\TechNative Bootcamp\Code" with the Live Server. Then to view it I go to [http://127.0.0.1:5500/milliways_restaurant/](http://127.0.0.1:5500/milliways_restaurant/).

I also added a link to "Credits and Attributions" at the bottom, to [https://github.com/technative-academy/milliways_restaurant/blob/main/credits](https://github.com/technative-academy/milliways_restaurant/blob/main/credits) . It should maybe be changed to credits.txt or credits.md though.

Is that good?

**Comment by NicoClack** [comment]
We should probably also add something about the absolute paths to the README when we add a section on how to run it locally.

**Comment by Jo-Pickering** [comment]
It's a shame it's gotten so complicated, I'd have probably voted to keep relative had I known.  But sure.  Let's keep pushing forwards!

**Comment by NicoClack** [comment]
@Jo-Pickering I guess it can be considered future-proofing though. It makes things a little more complicated now, but it'll make adding and maintaining new pages easier. There might not be much in it though as the only thing you have to change for development is where the Live Server is run from.

**Comment by NicoClack** [comment]
To match with the upcoming credits.md file

**Pull request merged**
