### PR TITLE
CSS for about section and page titles.

### PR DESCRIPTION
**Pull request by Jo-Pickering**
Add styling for the about/ blurb section on the about page.
Add very basic styling for H1 and p for the page.

Requesting a merge so I can re-branch and pull Helders content and finalise the page spacing etc.

### CODE REVIEW

**Comment by Jo-Pickering** [comment]
Sorry - also fixed comment syntax in about's index.html footer!

**Review by HelderBalbino — APPROVED** [review]
great work, happy for you to merge.

**Comment by NicoClack** [comment]
Looks good on mobile but it might need tweaking on desktop to stop it getting too wide. It might be fine on smaller monitors with a larger UI scaling but it looks like this on mine:

image

Although now that I think about it, I wonder if there's actually anything wrong with this. I guess maybe it just looks a bit overly centered to me?

**Comment by NicoClack** [comment]
Here's Wikipedia for context if that's any help:

image

**Comment by NicoClack** [comment]
Maybe it's because it doesn't use up much of the vertical space?

**Comment by Jo-Pickering** [comment]
This is part of the reason I'd like to merge now.  My next aim is to work on the wider page layout because I can see issues here, but I don't want to start implementing flexboxes at the page level without being able to see Helder's content too (as it will also affect that).  Part of that will be popping a max width on the main for larger screen sizes and generally sorting out the gaps/spacing between elements.

Is there anything you want changed or removed now?

**Comment by NicoClack** [comment]
Yeah, that sounds good. I'm not great with CSS and/or design so I'm just raising the problem, I don't really have a solution. Happy to merge.

**Pull request merged**
