### PR TITLE
Facts HTML and icons

### PR DESCRIPTION
**Pull request by Jo-Pickering**
HTML information and icons added for the 'Facts' section.

CSS for layout and scaling to come in a later pull.

### CODE REVIEW

**Comment by NicoClack** [comment]
The content looks good. Do those icons have SVG versions we can use instead though?

**Comment by Jo-Pickering** [comment]
I will find svgs for you and re-commit.

**Comment by Jo-Pickering** [comment]
Update @hedgehog125 - svgs are only available on premium.  Can they stay as pngs? I feel like it's not a great use of my time to hunt through and find different images at this point...

**Comment by NicoClack** [comment]
@Jo-Pickering Yeah, PNGs are probably fine. What license are they under though?

**Comment by Jo-Pickering** [comment]
This is the site I've gotten them from : https://www.flaticon.com/search?word=ai
I've saved all the links they've given me:
<a href="https://www.flaticon.com/free-icons/menu" title="menu icons">Menu icons created by Freepik - Flaticon</a>

<a href="https://www.flaticon.com/free-icons/travel" title="travel icons">Travel icons created by Freepik - Flaticon</a>

<a href="https://www.flaticon.com/free-icons/ai" title="ai icons">Ai icons created by photo3idea_studio - Flaticon</a>

<a href="https://www.flaticon.com/free-icons/fast-food" title="fast food icons">Fast food icons created by Darius Dan - Flaticon</a>

*also updating 1 image because I didn't have the link saved.

**Comment by hedgehog125** [comment]
To match with the upcoming credits.md file

**Pull request merged**
