### PR TITLE
add hero section with a h1 and a paragraph

### PR DESCRIPTION
**Pull request by HelderBalbino**
I have added a hero section

### CODE REVIEW

**Review by Jo-Pickering — CHANGES_REQUESTED** [review]
Hi Helder,

Could you please edit the text so that enclosed in p moved to H1 as discussed on our call?  Also, where the the image going?  The design shows it as a block within the HTML.

Thanks!

**Comment by NicoClack** [comment]
Looks good to me other than that. I think that naming follows BEM.

**Comment by HelderBalbino** [comment]
I have added the changes, also the image is going in the css as a background image

**Comment by Jo-Pickering** [comment]
@HelderBalbino Ohhhh.  I didn't realise we'd agreed on that. It's very different from the design brief. I doubt the image I made will hold up to that.  @hedgehog125 what are your thoughts?

**Comment by NicoClack** [comment]
@Jo-Pickering I forgot about that too. The notes say it'll read "Click to View Menu", so that'll require a few changes.

Should we add some kind of aria label for it as a replacement for an alt if it's not an `img`? I'm not sure it's completely decorative.

**Pull request merged**
