### PR TITLE
css for tabs section

### PR DESCRIPTION
**Pull request by Jo-Pickering**
**css for Tabs section**

- designed for mobile first
- flexboxes added
- created 'tabs' class to overwrite button features from elsewhere on the homepage.
- created 'selected' class to show which tab is selected.
- design elements taken from design brief
- swapped flex direction at large screen size
- swapped tab position for larger s creen size, including border radius and border line as appropriate.

### CODE REVIEW

**Comment by HelderBalbino** [comment]
loooks amazing Jo!
amazing work!

**Comment by NicoClack** [comment]
Looks great, thanks for taking care of that. Only thing is that the buttons growing is causing the images to shift about. Do we need these ones to grow?

**Comment by Jo-Pickering** [comment]
Hover states for Nico's tabs edited

**Comment by NicoClack** [comment]
Yep, looks good to me

**Pull request merged**
