### PR TITLE
Add Footer CSS

### PR DESCRIPTION
**Pull request by NicoClack**
I added the CSS for the footer.

Desktop:
image

Mobile:
image

### For the Backlog

 - Add a max width once the page has one

### Unrelated Changes

 - Fixes a number of broken links

(Finally) resolves: https://trello.com/c/bmdVsaS9

### CODE REVIEW

**Review by HelderBalbino — APPROVED** [review]
It looks very professional and i can see your attention to detail Nico!
Very happy to merge it.
Well done!

**Comment by NicoClack** [comment]
One other thing I forgot: the social media buttons are positioned slightly incorrectly on desktop. I think they're supposed to be centred with the copyright text, but I wasn't sure how to do that while keeping the text in the same place. Probably at most a backlog task?

image

**Comment by Jo-Pickering** [comment]
Looking good Nico.

As with the header, the space it takes up seems a little overweighted.  Reducing the font size could have helped (especially on mobile).  However, as discussed, I'd much rather you move on!

Merge away :D

**Review by Jo-Pickering — APPROVED** [review]

**Comment by Jo-Pickering** [comment]
Yep - 100% backlog task with the socials Nico!!  I'd love to see your JS prowess in action!

**Comment by NicoClack** [comment]
@Jo-Pickering I think the design originally used quite a lot of space. But yeah, we can change it later.

**Pull request merged**
